env:
    browser: true
    es2023: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - react
settings:
    react:
        version: detect
ignorePatterns:
    - node_modules
    - public
    - coverage
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    max-len:
        - warn
        -   code: 200
            ignoreComments: true
    quotes:
        - error
        - single
    semi:
        - error
        - never
    no-duplicate-imports:
        - error
        - includeExports: true
    sort-imports:
        - error
        -   allowSeparatedGroups: false
            ignoreCase: false
            ignoreDeclarationSort: true
            memberSyntaxSortOrder:
                - none
                - all
                - multiple
                - single
    '@typescript-eslint/no-inferrable-types': off
    '@typescript-eslint/no-unsafe-assignment': warn
    no-unused-vars: off
    '@typescript-eslint/no-unused-vars': 
        - warn
        -   args: none
            varsIgnorePattern: React
    '@typescript-eslint/unbound-method': off
    arrow-spacing:
        - error
        -   before: true
            after: true
    comma-dangle:
        - error
        - always-multiline
    eol-last: error
    no-multiple-empty-lines:
        - error
        -   max: 1
            maxBOF: 0
    no-trailing-spaces: error
    object-curly-spacing:
        - error
        - always
    react/jsx-uses-react: off
    react/react-in-jsx-scope: off
